In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:

# Importing the dataset
dataset = pd.read_csv('breast_cancer.csv')
X = dataset.iloc[:250, 3:15].values
y = dataset.iloc[:250, 15].values


In [3]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
print(X_train)

[[1.464e+01 5.879e+01 2.440e+02 ... 5.262e-01 8.522e-01 3.168e+00]
 [2.018e+01 7.610e+01 4.198e+02 ... 5.018e-01 1.693e+00 3.926e+00]
 [2.187e+01 1.821e+02 2.250e+03 ... 8.361e-01 1.481e+00 5.820e+00]
 ...
 [1.667e+01 9.864e+01 6.825e+02 ... 4.266e-01 9.489e-01 2.989e+00]
 [1.866e+01 8.598e+01 5.346e+02 ... 2.871e-01 8.937e-01 1.897e+00]
 [1.189e+01 1.025e+02 7.369e+02 ... 4.209e-01 6.583e-01 2.805e+00]]


In [7]:
print(X_test)

[[1.347e+01 9.251e+01 6.412e+02 9.906e-02 7.624e-02 5.724e-02 4.603e-02
  2.075e-01 5.448e-02 5.220e-01 8.121e-01 3.763e+00]
 [2.020e+01 1.662e+02 1.761e+03 1.447e-01 2.867e-01 4.268e-01 2.012e-01
  2.655e-01 6.877e-02 1.509e+00 3.120e+00 9.807e+00]
 [1.476e+01 8.474e+01 5.517e+02 7.355e-02 5.055e-02 3.261e-02 2.648e-02
  1.386e-01 5.318e-02 4.057e-01 1.153e+00 2.701e+00]
 [1.946e+01 1.084e+02 8.802e+02 7.445e-02 7.223e-02 5.150e-02 2.771e-02
  1.844e-01 5.268e-02 4.789e-01 2.060e+00 3.479e+00]
 [1.534e+01 8.531e+01 5.389e+02 9.384e-02 8.498e-02 9.293e-02 3.483e-02
  1.822e-01 6.207e-02 2.710e-01 7.927e-01 1.819e+00]
 [1.594e+01 1.263e+02 1.157e+03 8.694e-02 1.185e-01 1.193e-01 9.667e-02
  1.741e-01 5.176e-02 1.000e+00 6.336e-01 6.971e+00]
 [2.249e+01 1.275e+02 1.148e+03 8.523e-02 1.428e-01 1.114e-01 6.772e-02
  1.767e-01 5.529e-02 4.357e-01 1.073e+00 3.833e+00]
 [2.629e+01 1.291e+02 1.132e+03 1.215e-01 1.791e-01 1.937e-01 1.469e-01
  1.634e-01 7.224e-02 5.190e-01 2.910e+00 5.801e+00]


In [4]:
# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [5]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [8]:
print(y_pred)

[ 23.56  67.78  43.4  106.    14.66  74.08  70.01  49.7   22.79  15.75
  87.87  16.64  67.78  21.2   16.35  21.03  31.    19.91  34.44  34.62
  60.41  74.08  74.08  49.7   50.96  40.51  25.13  17.47  18.52  16.64
  25.44  41.    18.39  19.87  16.64  19.87  18.62  17.67  41.18  16.41
  54.18 104.9   16.64  16.35  41.18  24.62  80.6   15.09  27.23  19.87]
